#dir.create("dataset")
#dir.create("scripts")
#dir.create("figs")
#dir.create("report")
#dir.create("docs")
#dir.create("download")
library(tidyverse)
library(tidytext)
library(rio)
library(stringr)
library(xml2)
library(httr)
library(RCurl)
library(quanteda)
library(qdapRegex)
library(rtweet)
library(rvest)
library(lubridate)
library(scales)
library(stargazer)
library(kableExtra)
library(plotly)
library(tm)
library(syuzhet)

#run after a corpus has been created
library(rJava)
library(qdap)
