#dir.create("dataset")
#dir.create("scripts")
#dir.create("figs")
#dir.create("report")
#dir.create("docs")
#dir.create("download")

library(tidyverse)
library(tidytext)
library(rio)
library(stringr)
library(xml2)
library(httr)
library(RCurl)
library(quanteda)
library(rtweet)
library(rvest)
